/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn ampxiInit(servhandle: Handle) -> Result;
    pub fn ampxiExit();
    pub fn AMPXI_WriteTWLSavedata(titleid: u64_, buffer: *mut u8_, size: u32_,
                                  image_filepos: u32_, section_type: u8_,
                                  operation: u8_) -> Result;
    pub fn AMPXI_InstallTitlesFinish(mediaType: FS_MediaType, db: u8_,
                                     titlecount: u32_, tidlist: *mut u64_)
     -> Result;
}
use ::types::*;
use super::fs::FS_MediaType;
