/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn cfgnorInit(value: u8_) -> Result;
    pub fn cfgnorExit();
    pub fn cfgnorDumpFlash(buf: *mut u32_, size: u32_) -> Result;
    pub fn cfgnorWriteFlash(buf: *mut u32_, size: u32_) -> Result;
    pub fn CFGNOR_Initialize(value: u8_) -> Result;
    pub fn CFGNOR_Shutdown() -> Result;
    pub fn CFGNOR_ReadData(offset: u32_, buf: *mut u32_, size: u32_)
     -> Result;
    pub fn CFGNOR_WriteData(offset: u32_, buf: *mut u32_, size: u32_)
     -> Result;
}
use ::types::*;
