/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum Enum_Unnamed1 {
    GSPLCD_SCREEN_TOP = 1,
    GSPLCD_SCREEN_BOTTOM = 2,
    GSPLCD_SCREEN_BOTH = 3,
}
extern "C" {
    pub fn gspLcdInit() -> Result;
    pub fn gspLcdExit();
    pub fn GSPLCD_PowerOnBacklight(screen: u32_) -> Result;
    pub fn GSPLCD_PowerOffBacklight(screen: u32_) -> Result;
    pub fn GSPLCD_GetVendors(vendors: *mut u8_) -> Result;
}
use ::types::*;
