/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn iruInit(sharedmem_addr: *mut u32_, sharedmem_size: u32_) -> Result;
    pub fn iruExit();
    pub fn iruGetServHandle() -> Handle;
    pub fn iruSendData(buf: *mut u8_, size: u32_, wait: u8) -> Result;
    pub fn iruRecvData(buf: *mut u8_, size: u32_, flag: u8_,
                       transfercount: *mut u32_, wait: u8) -> Result;
    pub fn IRU_Initialize() -> Result;
    pub fn IRU_Shutdown() -> Result;
    pub fn IRU_StartSendTransfer(buf: *mut u8_, size: u32_) -> Result;
    pub fn IRU_WaitSendTransfer() -> Result;
    pub fn IRU_StartRecvTransfer(size: u32_, flag: u8_) -> Result;
    pub fn IRU_WaitRecvTransfer(transfercount: *mut u32_) -> Result;
    pub fn IRU_SetBitRate(value: u8_) -> Result;
    pub fn IRU_GetBitRate(out: *mut u8_) -> Result;
    pub fn IRU_SetIRLEDState(value: u32_) -> Result;
    pub fn IRU_GetIRLEDRecvState(out: *mut u32_) -> Result;
}
use ::types::*;
