/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub static mut irrstMemHandle: Handle;
    pub static mut irrstSharedMem: *mut vu32;
}
extern "C" {
    pub fn irrstInit() -> Result;
    pub fn irrstExit();
    pub fn irrstScanInput();
    pub fn irrstKeysHeld() -> u32_;
    pub fn irrstCstickRead(pos: *mut circlePosition);
    pub fn irrstWaitForEvent(nextEvent: u8);
    pub fn IRRST_GetHandles(outMemHandle: *mut Handle,
                            outEventHandle: *mut Handle) -> Result;
    pub fn IRRST_Initialize(unk1: u32_, unk2: u8_) -> Result;
    pub fn IRRST_Shutdown() -> Result;
}
use ::types::*;
use super::hid::*;
