/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn nsInit() -> Result;
    pub fn nsExit();
    pub fn NS_LaunchFIRM(titleid: u64_) -> Result;
    pub fn NS_LaunchTitle(titleid: u64_, launch_flags: u32_,
                          procid: *mut u32_) -> Result;
    pub fn NS_LaunchApplicationFIRM(titleid: u64_, flags: u32_) -> Result;
    pub fn NS_RebootToTitle(mediatype: u8_, titleid: u64_) -> Result;
    pub fn NS_TerminateProcessTID(titleid: u64_) -> Result;
}
use ::types::*;
