/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn ptmSysmInit() -> Result;
    pub fn ptmSysmExit();
    pub fn PTMSYSM_CheckNew3DS() -> Result;
    pub fn PTMSYSM_ConfigureNew3DSCPU(value: u8_) -> Result;
    pub fn PTMSYSM_ShutdownAsync(timeout: u64_) -> Result;
    pub fn PTMSYSM_RebootAsync(timeout: u64_) -> Result;
}
use ::types::*;
