/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn ptmuInit() -> Result;
    pub fn ptmuExit();
    pub fn PTMU_GetShellState(out: *mut u8_) -> Result;
    pub fn PTMU_GetBatteryLevel(out: *mut u8_) -> Result;
    pub fn PTMU_GetBatteryChargeState(out: *mut u8_) -> Result;
    pub fn PTMU_GetPedometerState(out: *mut u8_) -> Result;
    pub fn PTMU_GetTotalStepCount(steps: *mut u32_) -> Result;
}
use ::types::*;
