/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub static mut gpuCmdBuf: *mut u32_;
    pub static mut gpuCmdBufSize: u32_;
    pub static mut gpuCmdBufOffset: u32_;
}
extern "C" {
    pub fn GPUCMD_SetBuffer(adr: *mut u32_, size: u32_, offset: u32_);
    pub fn GPUCMD_SetBufferOffset(offset: u32_);
    pub fn GPUCMD_GetBuffer(adr: *mut *mut u32_, size: *mut u32_,
                            offset: *mut u32_);
    pub fn GPUCMD_AddRawCommands(cmd: *const u32_, size: u32_);
    pub fn GPUCMD_Run();
    pub fn GPUCMD_FlushAndRun();
    pub fn GPUCMD_Add(header: u32_, param: *const u32_, paramlength: u32_);
    pub fn GPUCMD_Finalize();
    pub fn f32tof16(f: f32) -> u32_;
    pub fn f32tof20(f: f32) -> u32_;
    pub fn f32tof24(f: f32) -> u32_;
    pub fn f32tof31(f: f32) -> u32_;
}
use ::types::*;
