/* automatically generated by rust-bindgen */

#[inline]
pub fn GPUCMD_HEADER(incremental: u32, mask: u32, reg: u32) -> u32{
    (((incremental)<<31)|(((mask)&0xF)<<16)|((reg)&0x3FF))
}

extern "C" {
    pub static mut gpuCmdBuf: *mut u32;
    pub static mut gpuCmdBufSize: u32;
    pub static mut gpuCmdBufOffset: u32;

    pub fn GPUCMD_SetBuffer(adr: *mut u32, size: u32, offset: u32);
    pub fn GPUCMD_SetBufferOffset(offset: u32);
    pub fn GPUCMD_GetBuffer(adr: *mut *mut u32, size: *mut u32,
                            offset: *mut u32);
    pub fn GPUCMD_AddRawCommands(cmd: *mut u32, size: u32);
    pub fn GPUCMD_Run();
    pub fn GPUCMD_FlushAndRun();
    pub fn GPUCMD_Add(header: u32, param: *mut u32, paramlength: u32);
    pub fn GPUCMD_Finalize();
    pub fn f32tof16(f: f32) -> u32;
    pub fn f32tof20(f: f32) -> u32;
    pub fn f32tof24(f: f32) -> u32;
    pub fn f32tof31(f: f32) -> u32; 
}
